package com.ahmudz.librarymanagementsystem;

import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Mahmud
 */
public class CreateAccountWindow extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccountWindow
     */
    public CreateAccountWindow() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(22, 84, 109));
        setTitle("Create New Account");
        setJLabelColors(Color.WHITE);

        userTypeComboBox.addItem("student");
        if (StateManager.role.equals("admin")) {
            userTypeComboBox.addItem("admin");
            lginButton.setVisible(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNameLabel = new javax.swing.JLabel();
        createStudentNameTextField = new javax.swing.JTextField();
        userIDLabel = new javax.swing.JLabel();
        createStudentIDTextField = new javax.swing.JTextField();
        userTypeLabel = new javax.swing.JLabel();
        userTypeComboBox = new javax.swing.JComboBox<>();
        userPassLabel = new javax.swing.JLabel();
        createPasswordTextField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        lginButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userNameLabel.setText("Student Name :");

        userIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userIDLabel.setText("Student ID : ");

        userTypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userTypeLabel.setText("User Type : ");

        userTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTypeComboBoxActionPerformed(evt);
            }
        });

        userPassLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userPassLabel.setText("Password : ");

        createButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        lginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lginButton.setText("Login");
        lginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lginButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create a New Account");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(userIDLabel)
                        .addComponent(userNameLabel)
                        .addComponent(userPassLabel))
                    .addComponent(userTypeLabel))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(lginButton))
                    .addComponent(userTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createStudentIDTextField)
                    .addComponent(createStudentNameTextField)
                    .addComponent(createPasswordTextField))
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userTypeLabel)
                    .addComponent(userTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userIDLabel)
                    .addComponent(createStudentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(createStudentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userPassLabel)
                    .addComponent(createPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(lginButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(exitButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setJLabelColors(Color color) {
        for (java.awt.Component c : this.getContentPane().getComponents()) {
            if (c instanceof JLabel) {
                ((JLabel) c).setForeground(color);
            }
        }
    }

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed

        String stdID = createStudentIDTextField.getText();
        String stdName = createStudentNameTextField.getText();
        String stdPassword = createPasswordTextField.getText();

        if (stdName.isEmpty()|| stdPassword.isEmpty() || stdID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Fill All TextField");
            return;
        }

        DatabaseConnection con = new DatabaseConnection();

        try {
            String userType = (String) userTypeComboBox.getSelectedItem();

            System.out.println("" + userType);

            if (userType.equals("admin")) {
                con.execute("insert into admins(id, name, password) values (?, ?, ?);", stdID, stdName, stdPassword);
                createStudentIDTextField.setText("");
                createStudentNameTextField.setText("");
                createPasswordTextField.setText("");
            }

            if (userType.equals("student")) {
                con.execute("insert into students(roll, name, password) values (?, ?, ?);", stdID, stdName, stdPassword);
                createStudentIDTextField.setText("");
                createStudentNameTextField.setText("");
                createPasswordTextField.setText("");
            }

            JOptionPane.showMessageDialog(this, "Account created. Please login.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Failed to create account");
        }


    }//GEN-LAST:event_createButtonActionPerformed

    private void lginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lginButtonActionPerformed

        this.setVisible(false);
        LoginWindow ob = new LoginWindow();
        ob.setVisible(true);

    }//GEN-LAST:event_lginButtonActionPerformed

    private void userTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTypeComboBoxActionPerformed
        int type = userTypeComboBox.getSelectedIndex();
        System.out.println("" + type);

        if (type == 0) {
            userIDLabel.setText("Student ID:");
            userNameLabel.setText("Student Name:");
        }

        if (type == 1) {
            userIDLabel.setText("Admin ID:   ");
            userNameLabel.setText("Admin Name :  ");
        }

    }//GEN-LAST:event_userTypeComboBoxActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        int type = userTypeComboBox.getSelectedIndex();

        if (StateManager.role.equals("admin")) {
            this.setVisible(false);
            MainWindow ob = new MainWindow();
            ob.setVisible(true);
        } else {
            this.setVisible(false);
            LoginWindow ob = new LoginWindow();
            ob.setVisible(true);
        }

    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccountWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccountWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccountWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccountWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccountWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField createPasswordTextField;
    private javax.swing.JTextField createStudentIDTextField;
    private javax.swing.JTextField createStudentNameTextField;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lginButton;
    private javax.swing.JLabel userIDLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JLabel userPassLabel;
    private javax.swing.JComboBox<String> userTypeComboBox;
    private javax.swing.JLabel userTypeLabel;
    // End of variables declaration//GEN-END:variables
}
