package com.ahmudz.librarymanagementsystem;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class MainWindow extends javax.swing.JFrame {

    void hideButtons() {
        if (StateManager.role.equals("student")) {
            btnAddBook.setVisible(false);
            btnUpdateBook.setVisible(false);
            createNewForAdminBtn.setVisible(false);
            setTitle("Main Window (Student Panel)");
            btnIssueBook.setText("Borrow Books");

        } else {
            setTitle("Main Window (Admin Panel)");
//            btnIssueBook.setVisible(false);
            viewProfileButton.setVisible(false);
        }
    }

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();

        hideButtons();

        this.setSize(400, 320);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnShowBooks = new javax.swing.JButton();
        btnAddBook = new javax.swing.JButton();
        btnIssueBook = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        btnUpdateBook = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        issuedBookBtn = new javax.swing.JButton();
        viewProfileButton = new javax.swing.JButton();
        createNewForAdminBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(400, 320));
        getContentPane().setLayout(null);

        btnShowBooks.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnShowBooks.setText("Show Books");
        btnShowBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowBooksActionPerformed(evt);
            }
        });
        getContentPane().add(btnShowBooks);
        btnShowBooks.setBounds(70, 90, 120, 23);

        btnAddBook.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddBook.setText("Add Books");
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddBook);
        btnAddBook.setBounds(200, 90, 120, 23);

        btnIssueBook.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIssueBook.setText("Issue Books");
        btnIssueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnIssueBook);
        btnIssueBook.setBounds(70, 170, 120, 23);

        jLabel2.setFont(new java.awt.Font("Siyam Rupali", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("লাইব্রেরি ম্যানেজমেন্ট সিস্টেম");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 30, 250, 24);

        logoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBtn);
        logoutBtn.setBounds(20, 250, 80, 23);

        btnUpdateBook.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateBook.setText("Update Books");
        btnUpdateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateBook);
        btnUpdateBook.setBounds(200, 130, 120, 23);

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(310, 250, 60, 23);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Search Books");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 130, 120, 23);

        issuedBookBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        issuedBookBtn.setText("Issued Books");
        issuedBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuedBookBtnActionPerformed(evt);
            }
        });
        getContentPane().add(issuedBookBtn);
        issuedBookBtn.setBounds(200, 170, 120, 23);

        viewProfileButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewProfileButton.setText("View Profile");
        viewProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfileButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewProfileButton);
        viewProfileButton.setBounds(200, 90, 120, 23);

        createNewForAdminBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        createNewForAdminBtn.setText("Create an Account");
        createNewForAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewForAdminBtnActionPerformed(evt);
            }
        });
        getContentPane().add(createNewForAdminBtn);
        createNewForAdminBtn.setBounds(120, 210, 140, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 400, 300);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowBooksActionPerformed
        BookListWindow bookListWindow = new BookListWindow();

        bookListWindow.setVisible(true);

        StateManager.previousWindow = this;

        this.setVisible(false);
    }//GEN-LAST:event_btnShowBooksActionPerformed

    private void btnIssueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueBookActionPerformed

        IssueBook issueBookWin = new IssueBook();
        this.setVisible(false);
        issueBookWin.setVisible(true);


    }//GEN-LAST:event_btnIssueBookActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
        AddBookWindow addBookWindow = new AddBookWindow();

        addBookWindow.setVisible(true);

        StateManager.previousWindow = this;
        this.setVisible(false);
    }//GEN-LAST:event_btnAddBookActionPerformed

    private void btnUpdateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBookActionPerformed

        UpdateBookWindow updateWin = new UpdateBookWindow();

        StateManager.previousWindow = this;

        this.setVisible(false);

        updateWin.setVisible(true);
    }//GEN-LAST:event_btnUpdateBookActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed

        LoginWindow logWin = new LoginWindow();
        this.setVisible(false);
        logWin.setVisible(true);
        if (StateManager.role.equals("admin")) {
            StateManager.role = "";
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void issuedBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuedBookBtnActionPerformed
        try {
            this.setVisible(false);
            StateManager.previousWindow = this;

            IsuuedBookListWindow iblw = new IsuuedBookListWindow();
            iblw.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_issuedBookBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        StateManager.previousWindow = this;

        SearchBook obj = new SearchBook();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void viewProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfileButtonActionPerformed
        this.setVisible(false);
        StateManager.previousWindow = this;
        ProfileWindow ob;
        try {
            ob = new ProfileWindow();
            ob.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_viewProfileButtonActionPerformed

    private void createNewForAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewForAdminBtnActionPerformed
        CreateAccountWindow ob = new CreateAccountWindow();
        this.setVisible(false);
        ob.setVisible(true);


    }//GEN-LAST:event_createNewForAdminBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnIssueBook;
    private javax.swing.JButton btnShowBooks;
    private javax.swing.JButton btnUpdateBook;
    private javax.swing.JButton createNewForAdminBtn;
    private javax.swing.JButton issuedBookBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton viewProfileButton;
    // End of variables declaration//GEN-END:variables
}
